version: '3'
services:
  db:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      OPENAI__SECRET: ${OPENAI__SECRET}
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
volumes:
  mongodb_data_container:
